namespace ArcaSim.Application.Services.Mtxca;

/// <summary>Which table of the manual a code comes from: error and observation numbers are separate spaces, and each method has its own.</summary>
public enum MtxcaTable
{
    /// <summary>autorizarComprobante, plus the issuer's checks (pág. 16).</summary>
    Cae,

    /// <summary>informarComprobanteCAEA.</summary>
    Caea,

    /// <summary>solicitarCAEA, plus the issuer's checks.</summary>
    Request,

    /// <summary>informarCAEANoUtilizado and informarCAEANoUtilizadoPtoVta.</summary>
    Unused,

    /// <summary>The queries: consultarCAEA, consultarCAEAEntreFechas, consultarUltimoComprobanteAutorizado, consultarComprobante, consultarCondicionesIVAReceptor, consultarCotizacionMoneda.</summary>
    Query,
}

/// <summary>One code a validation produced: an error that rejects, or an observation that lets the voucher through.</summary>
public sealed record MtxcaFinding(int Code, string Text, bool Rejects);

/// <summary>
/// The codes ArcaSim's wsmtxca rules use, with the manual's text for each
/// (docs/arca/servicios/wsmtxca-codigos.json). The manual prints the condition
/// each code checks, not the descripcion the service returns, which no source
/// shows; ArcaSim answers with the manual's text.
/// </summary>
public static class MtxcaCodes
{
    public static MtxcaFinding Error(MtxcaTable table, int code) => new(code, Texts[(table, code, true)], true);

    public static MtxcaFinding Observation(MtxcaTable table, int code) => new(code, Texts[(table, code, false)], false);

    private const MtxcaTable Cae = MtxcaTable.Cae;
    private const MtxcaTable Caea = MtxcaTable.Caea;
    private const MtxcaTable Request = MtxcaTable.Request;
    private const MtxcaTable Unused = MtxcaTable.Unused;
    private const MtxcaTable Query = MtxcaTable.Query;

    private static readonly Dictionary<(MtxcaTable Table, int Code, bool Rejects), string> Texts = new()
    {
        [(Cae, 100, true)] = "Podrá ser: 1 – Factura A 2 – Nota de Débito A 3 – Nota de Crédito A 6 – Factura B 7 – Nota de Débito B 8 – Nota de Crédito B 51 – Factura A con leyenda OPERACIÓN SUJETA A RETENCIÓN 52 – Nota de Débito A con leyenda OPERACIÓN SUJETA A RETENCIÓN 53 – Nota de Crédito A con leyenda OPERACIÓN SUJETA A RETENCIÓN 201 - Factura de Crédito Electrónica MiPyMEs (FCE) A 202 - Nota de Débito Electrónica MiPyMEs (FCE) A 203 - Nota de Crédito Electrónica MiPyMEs (FCE) A 206- Factura de Crédito Electrónica MiPyMEs (FCE) B 207 - Nota de Débito Electrónica MiPyMEs (FCE) B 208 - Nota de Crédito Electrónica MiPyMEs (FCE) B Consultar método consultarTiposComprobante",
        [(Cae, 101, true)] = "Debe ser del tipo habilitado para el régimen CAE Codificación de Productos – Web Services y no debe estar bloqueado. Consultar método consultarPuntosVenta o consultarPuntosVentaCAE",
        [(Cae, 102, true)] = "El número de comprobante informado debe ser mayor en 1 al último informado para igual punto de venta y tipo de comprobante. De no existir comprobante informado para igual punto de venta y codigoTipoComprobante, el número de comprobante debe ser igual a 1 (uno)",
        [(Cae, 103, true)] = "Opcional. Para <codigoConcepto> igual a 1, la fecha de emisión del comprobante puede ser hasta 5 días anteriores o posteriores respecto de la fecha de generación, pero sin extenderse al mes siguiente; si se indica <codigoConcepto> igual a 2 ó 3 puede ser hasta 10 días anteriores o posteriores a la fecha de generación Obs.: Si no se envía se le asignará la fecha de proceso.",
        [(Cae, 104, true)] = "La fecha de emisión debe ser mayor o igual a la fecha de emisión del último comprobante del mismo tipo e igual número de punto de venta.",
        [(Cae, 105, true)] = "No debe informarse",
        [(Cae, 106, true)] = "No debe informarse",
        [(Cae, 107, true)] = "No debe informarse",
        [(Cae, 108, true)] = "Si se informa uno de los campos debe informarse el otro.",
        [(Cae, 110, true)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52, 53, 201, 202 ó 203: Deberá ser igual a la sumatoria de <importeItem> menos <importeIVA> para la totalidad de los ítems con <codigoCondicionIVA> igual a 3, 4, 5 ó 6. Si <codigoTipoComprobante> es igual a 6, 7 , 8, 206, 207 u 208: Deberá ser igual a la sumatoria de <importeItem> menos el IVA correspondiente (calculado en base al importe y la alícuota de cada ítem), para la totalidad de los ítems con <codigoCondicionIVA> igual a 3, 4, 5 ó 6. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems gravados *",
        [(Cae, 111, true)] = "Deberá coincidir con la sumatoria de <importeItem> para los ítems con <codigoCondicionIVA> igual a 1. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems no gravados *",
        [(Cae, 112, true)] = "Deberá coincidir con la sumatoria de <importeItem> para los ítems con <codigoCondicionIVA> igual a 2. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems exentos *",
        [(Cae, 113, true)] = "Deberá coincidir con la sumatoria de los campos <importeNoGravado>, <importeGravado>, <importeExento>. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 *",
        [(Cae, 114, true)] = "Debe ser igual a la sumatoria de la totalidad de los campos <otroTributo><importe> (dentro de <arrayOtrosTributos>). Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de tributos *",
        [(Cae, 115, true)] = "Debe ser igual a <importeSubtotal>+ <importeOtrosTributos> + sumatoria de <subtotalIVA><importe> (dentro del arraySubtotalesIVA). Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 *",
        [(Cae, 116, true)] = "Debe ser igual a <importeOtrosTributos> + la sumatoria de la totalidad de los campos <importeItem>. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems *",
        [(Cae, 117, true)] = "Deberá ser igual a alguno de los valores permitidos. Consultar método consultarMonedas",
        [(Cae, 118, true)] = "En caso de enviar la marca de que el pago del comprobante se realiza en la misma moneda extranjera para comprobantes que no sean facturas. Unicamente se puede utilizar con los códigos habilitados (1,6,51,201,206)",
        [(Cae, 119, true)] = "No podrá ser inferior al 2% ni superior en un 400% del que suministra ARCA como orientativo de acuerdo a la cotización oficial",
        [(Cae, 120, true)] = "Debe ser igual a 1 (uno) si <codigoMoneda> es igual a PES",
        [(Cae, 121, true)] = "Deberá ser igual a alguno de los siguientes valores: 1 – Productos 2 – Servicios 3 – Productos y Servicios",
        [(Cae, 122, true)] = "Opcional. Debe informarse si <codigoConcepto> es igual a 2 ó 3. En otro caso no corresponde.",
        [(Cae, 123, true)] = "Opcional. Debe informarse si <codigoConcepto> es igual a 2 ó 3. En otro caso no corresponde.",
        [(Cae, 124, true)] = "Opcional. Debe informarse si <codigoConcepto> es igual a 2 ó 3. En otro caso no corresponde.",
        [(Cae, 125, true)] = "La fecha de vencimiento de pago debe ser posterior o igual a la fecha de emisión.",
        [(Cae, 127, true)] = "Opcional. Debe informarse si algún ítem tiene <codigoCondicionIVA> igual a 4, 5 ó 6. En otro caso no corresponde.",
        [(Cae, 128, true)] = "Opcionales. Deberán informarse en los siguientes casos: - cuando <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52, 53, 201, 202, 203, 206, 207 ó 208. -cuando <codigoTipoComprobante> es igual a 6, 7 u 8 y el importe total del comprobante <importeTotal> es mayor ó igual al monto en pesos resultante según RG4444.",
        [(Cae, 129, true)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52, 53, 201, 202, 203, 206, 207 ó 208. <codigoTipoDocumento> deberá ser igual a 80 (CUIT)",
        [(Cae, 131, true)] = "El Receptor no puede ser igual al Emisor",
        [(Cae, 132, true)] = "Deberá ser igual a alguno de los valores permitidos. Consultar método consultarTiposDocumento",
        [(Cae, 133, true)] = "La Fecha de Servicio desde debe ser menor o igual a la Fecha de Servicio Hasta",
        [(Cae, 135, true)] = "Solicitudes de autorización para un mismo punto de venta y tipo de comprobante deben ser enviadas en forma sincrónica: si el WS recibe una nueva solicitud para un punto de venta y tipo de comprobante dado mientras la anterior está siendo procesada, la nueva solicitud será rechazada",
        [(Cae, 145, true)] = "Falta incluir en la sección OtrosTributos la Percepción de IVA No Categorizado (ID 13), según lo dispuesto por la RG 2126/2006. Se debe informar el tributo <codigo> 13 (Percepción de IVA No Categorizado) con un <importe> mayor a 0 (cero) dentro del nodo <arrayOtrosTributos> cuando se cumplan simultáneamente las siguientes condiciones: - <codigoTipoComprobante> corresponda a un comprobante clase B (6, 7 u 8). - <codigoTipoDocumento> sea igual a 80 (CUIT). - <numeroDocumento> corresponda a 23000000000 (No Categorizado). - La suma de <importeGravado> más la sumatoria de los campos <importe> dentro de <arraySubtotalesIVA> sea mayor a 0 (cero).",
        [(Cae, 146, true)] = "La fecha/hora de generación solo debe informarse para comprobantes CAEA",
        [(Cae, 148, true)] = "Si <codigoTipoComprobante> es igual a 201 ó 206. La Fecha de Vencimiento de Pago es obligatorio para Facturas de Crédito MiPyME",
        [(Cae, 149, true)] = "Si <codigoTipoComprobante> es igual a 202, 203, 207 ó 208. La Fecha de Vencimiento de Pago no debe informarse para Notas de Crédito o Débito de las Facturas de Crédito MiPYME",
        [(Cae, 159, true)] = "Si <codigoTipoComprobante> es igual a 202, 203, 207 ó 208 perteneciente a Factura de Crédito Electrónica no corresponde informar un periodo de comprobantes asociados.",
        [(Cae, 160, true)] = "Si <codigoTipoComprobante> es igual a 2, 3, 7, 8, 52 ó 53. Falta informar comprobante/s asociado/s puntual del tipo factura, nota de debito o nota de crédito válido/s o informar un período de comprobantes asociados válido",
        [(Cae, 161, true)] = "Si <codigoTipoComprobante> es igual a 2, 3, 7, 8, 52 ó 53. No debe informar un período de comprobantes asociados cuando informa comprobante/s asociado/s puntual del tipo factura, nota de debito o nota de crédito",
        [(Cae, 162, true)] = "Si <codigoTipoComprobante> es igual a 1, 2, 51, 201 ó 206 correspondientes a Facturas no corresponde informar un periodo de comprobantes asociados.",
        [(Cae, 164, true)] = "En caso de enviar un valor inválido para la marca de que el pago de la factura se realiza en la misma moneda extranjera. Los valores válidos son S, N o vacío",
        [(Cae, 166, true)] = "Si <codigo> se encuentra mas de una vez en el array de actividades (no admite repetidos). Ver el Anexo de Rubros de Actividades y Remitos",
        [(Cae, 167, true)] = "Si <codigo> no se encuentra entre las actividades vigentes para la cuit representada. Ver el Anexo de Rubros de Actividades y Remitos",
        [(Cae, 169, true)] = "En caso de enviar la marca de que el pago de la factura se realiza en la misma moneda extranjera y enviar como código de moneda el Peso Argentino",
        [(Cae, 194, true)] = "El campo es obligatorio a excepción de los casos para los cuales se envia el campo cancelaEnMismaMonedaExtranjera y se puede obtener la cotizacion asociada al codigoMoneda si esta es del grupo de monedas del Banco de la Nación Argentina (ver Anexo Monedas BNA)",
        [(Cae, 195, true)] = "No es posible indicar una cotización negativa",
        [(Cae, 342, true)] = "Si <numeroDocumento> es la CUIT para Sujeto No Categorizado (23000000000) y el <codigoTipoDocumento> es distinto de B (6, 7 u 8) o si la <condicionIVAReceptor> no se corresponde con Sujeto No Categorizado",
        [(Cae, 200, true)] = "Deberá ser igual a 88 o 990 si el tipo de comprobante cuya autorización se solicita es igual a 1, 6 o 51 Deberá ser igual a 1, 2, 3, 88 o 990 si el tipo de comprobante cuya autorización se solicita es igual a 2 o 3. Deberá ser igual a 6, 7, 8, 88 o 990 si el tipo de comprobante cuya autorización se solicita es igual a 7 u 8. Deberá ser igual a 51, 52, 53, 88 o 990 si el tipo de comprobante cuya autorización se solicita es igual a 52 o 53. Deberá ser igual a 201, 202, 203, 88, 91, 990 o 995 si el tipo de comprobante cuya autorización se solicita es igual a 202 o 203. Deberá ser igual a 206, 207, 208, 88, 91, 990 o 995 si el tipo de comprobante cuya autorización se solicita es igual a 207 u 208.",
        [(Cae, 203, true)] = "Deberá ser igual a 1, 2, 3, 6, 7, 8, 51, 52, 53, 201, 202, 203, 206, 207, 208, 88, 91, 990 o 995.",
        [(Cae, 2200, true)] = "La fechaHasta debe ser posterior o igual fechaDesde",
        [(Cae, 2201, true)] = "La fechaHasta del periodoComprobantesAsociados debe ser anterior o igual a la fecha de emisión del comprobante por el cual se está solicitando la autorización",
        [(Cae, 300, true)] = "Valores permitidos: consultar método consultarTiposTributo",
        [(Cae, 301, true)] = "Opcional. Deberá informarse si <codigo> es igual a 99",
        [(Cae, 400, true)] = "Valores permitidos: 4, 5, 6",
        [(Cae, 401, true)] = "Para comprobantes clase “A” o “A con leyenda OPERACIÓN SUJETA A RETENCIÓN”: Deberá coincidir con la sumatoria de todos los <importeIVA> de <item> donde la alícuota de IVA coincida con la indicada, es decir, donde <codigoCondicionIVA> de <item> = <codigo> de <subtotalIVA>. Para comprobantes clase “B”: Deberá coincidir con la sumatoria de todos los importes IVA calculados en base al importe y alícuota IVA de <item> donde la alícuota de IVA coincida con la indicada, es decir, donde <codigoCondicionIVA> de <item> = <codigo> de <subtotalIVA>. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems con igual código de alícuota de IVA *",
        [(Cae, 402, true)] = "No se deberá repetir (no pueden incluírse dos subtotales IVA con el mismo código)",
        [(Cae, 403, true)] = "Si existen uno o más ítems con una determinada alícuota IVA, deberá existir el correspondiente subtotal IVA para dicha alícuota. No se sebe incluír un subtotal IVA si dicha alícuota no está presente en al menos un ítem.",
        [(Cae, 405, true)] = "La suma de los subtotales de IVA no puede ser negativa.",
        [(Cae, 500, true)] = "Opcional si <codigoUnidadMedida> es 99 ó 97, para el resto de los casos es obligatorio.",
        [(Cae, 501, true)] = "De informarse deberá ser mayor o igual a 1 (uno)",
        [(Cae, 502, true)] = "Longitud máxima 6 posiciones.",
        [(Cae, 503, true)] = "Opcional si <codigoUnidadMedida> es 99 ó 97, para el resto de los casos es obligatorio.",
        [(Cae, 505, true)] = "Opcional. Longitud máxima 50 posiciones.",
        [(Cae, 506, true)] = "Cantidad máxima de caracteres permitidos es 4000. Importante: no es necesario (ni recomendable) completar con espacios.",
        [(Cae, 507, true)] = "No corresponde para <codigoUnidadMedida> igual a 99 o 97. En otro caso es obligatorio.",
        [(Cae, 508, true)] = "Deberá ser alguno de los valores permitidos: consultar método consultarUnidadesMedida",
        [(Cae, 509, true)] = "No corresponde para <codigoUnidadMedida> igual a 99 o 97. En otro caso es obligatorio.",
        [(Cae, 510, true)] = "Opcional. No corresponde para <codigoUnidadMedida> igual a 99 o 97.",
        [(Cae, 511, true)] = "De informarse deberá ser menor o igual a <precioUnitario>*<cantidad>",
        [(Cae, 512, true)] = "Deberá coincidir con alguno de los valores permitidos: consultar método consultarCondicionesIVA",
        [(Cae, 513, true)] = "Si <codigoUnidadMedida> es 99 deberá existir por lo menos otro ítem con igual <codigoCondicionIVA> y <codigoUnidadMedida> distinta a la informada para este ítem.",
        [(Cae, 514, true)] = "Obligatorio si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 ó 53. No corresponde para <codigoTipoComprobante> igual a 6, 7 u 8.",
        [(Cae, 515, true)] = "Para <codigoTipoComprobante> igual a 1, 2 ó 3 y unidad de medida distinto a 95, 97 o 99, deberá ser igual a (<precioUnitario> * <cantidad> -<importeBonificacion>) * alícuota de IVA correspondiente. Para <codigoTipoComprobante> igual a 1, 2, 3, 51, 52 ó 53 y unidad de medida igual a 95 deberá ser igual a (-1) * (<precioUnitario> * <cantidad> - <importeBonificacion>) * alícuota de IVA correspondiente. Para <codigoTipoComprobante> igual a 1, 2, 3, 51, 52 ó 53 y unidad de medida igual a 97 o 99, deberá ser igual a <importeItem> - <importeItem> / (1 + alícuota de IVA correspondiente). El error relativo porcentual deberá ser <= 0.01% o el error absoluto <= 0.01 *",
        [(Cae, 516, true)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 ó 53 y <codigoUnidadMedida> es 99, el valor absoluto de la sumatoria de los importes ingresados para este campo no puede superar a la sumatoria de los importes <importeIVA> informado con la misma alícuota. El error relativo porcentual deberá ser <= 0.01% o el error absoluto <= 0.01 *",
        [(Cae, 517, true)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 ó 53 y <codigoUnidadMedida> es: - 99 deberá ser menor o igual a 0 (cero), - 97 podrá ser menor, mayor o igual a 0 (cero). - 95 deberá ser menor o igual a 0 (cero), - Cualquier otro caso deberá ser mayor o igual a 0 (cero).",
        [(Cae, 518, true)] = "Si <codigoUnidadMedida> es: - 99 deberá ser menor a 0 (cero), - 97 podrá ser menor, o mayor igual a 0 (cero). - 95 deberá ser menor a 0 (cero), - Cualquier otro caso deberá ser mayor o igual a 0 (cero).",
        [(Cae, 519, true)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 ó 53 y <codigoUnidadMedida> es distinto a 95, 97 ó 99, deberá ser igual a (<precioUnitario> sin IVA * <cantidad> -<importeBonificacion>)*(1+alícuota). Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 ó 53 y <codigoUnidadMedida> es igual a 95 ser igual a (-1) * (<precioUnitario> sin IVA * <cantidad> -<importeBonificacion>)*(1+alícuota). Si <codigoTipoComprobante> es igual a 6, 7 u 8 y <codigoUnidadMedida> es distinto a 95, 97 ó 99 deberá ser igual a (<precioUnitario> con IVA * <cantidad> -<importeBonificacion>). Si <codigoTipoComprobante> es igual a 6, 7 u 8 y <codigoUnidadMedida> es igual a 95 ser igual a (-1) * (<precioUnitario> con IVA * <cantidad> -<importeBonificacion>). En ambos casos el error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 *",
        [(Cae, 520, true)] = "Si se informa el campo <unidadesMtx> entonces debe informarse el campo <codigoMtx> y viceversa.",
        [(Cae, 521, true)] = "Si <codigoCondicionIVA> es igual a 1, 2 ó 3 entonces <importeIVA> deberá ser igual a 0 (cero).",
        [(Cae, 320, true)] = "Valores permitidos: consultar método consultarTiposDatosAdicionales",
        [(Cae, 322, true)] = "No se puede incluír más de un dato adicional (sólo se permite un id por comprobante)",
        [(Cae, 420, true)] = "Si se informar el grupo de compradores debe tener mas de un comprador",
        [(Cae, 422, true)] = "El tipo de documento de los compradores debe ser CUIT, CUIL o CDI",
        [(Cae, 424, true)] = "El Porcentaje de Titularidad del Comprador debe ser mayor a 0 (cero)",
        [(Cae, 425, true)] = "El Porcentaje de Titularidad del Comprador debe ser menor a 100 (cien)",
        [(Cae, 427, true)] = "La suma de los porcentajes indicados en la lista de compradores debe ser igual a 100",
        [(Cae, 432, true)] = "Sólo se puede informar el arrayCompradores para codigoConcepto igual a 1 (Productos)",
        [(Cae, 433, true)] = "Si <codigoTipoComprobante> es igual a 201, 202, 203, 206, 207 ó 208, no puede informar compradores múltiples.",
        [(Cae, 109, false)] = "Si <codigoTipoDocumento> es igual a 80, 86 o 87, <numeroDocumento> debe ser válido y activo, excepto para <codigoTipoComprobante> 6, 7 u 8, <codigoTipoDocumento> 80 y <numeroDocumento> igual a 23000000000.",
        [(Cae, 130, false)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 ó 53 la CUIT del receptor debe encontrarse activa en IVA o en monotributo",
        [(Cae, 164, false)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 ó 53 la CUIT del receptor es activa en monotributo",
        [(Cae, 190, false)] = "Si no se informa la condición de IVA del Receptor (obligatoria) o bien se informa un valor no contemplado por el servicio. Ver método consultarCondicionesIVAReceptor",
        [(Cae, 191, false)] = "Si se informa una combinación invalida de Condición de IVA del Receptor y Tipo de Comprobante. Ver método consultarCondicionesIVAReceptor",
        [(Cae, 10000, true)] = "Debe encontrarse activa en el Sistema Registral",
        [(Cae, 10003, true)] = "Debe estar dado de alta en el Impuesto al Valor Agregado al momento del envío de la solicitud.",
        [(Caea, 700, true)] = "Podrá ser: 1 – Factura A 2 – Nota de Débito A 3 – Nota de Crédito A 6 – Factura B 7 – Nota de Débito B 8 – Nota de Crédito B 51 – Factura A con leyenda OPERACIÓN SUJETA A RETENCIÓN 52 – Nota de Débito A con leyenda OPERACIÓN SUJETA A RETENCIÓN 53 – Nota de Crédito A con leyenda OPERACIÓN SUJETA A RETENCIÓN 201 - Factura de Crédito Electrónica MiPyMEs (FCE) A 202 - Nota de Débito Electrónica MiPyMEs (FCE) A 203 - Nota de Crédito Electrónica MiPyMEs (FCE) A 206- Factura de Crédito Electrónica MiPyMEs (FCE) B 207 - Nota de Débito Electrónica MiPyMEs (FCE) B 208 - Nota de Crédito Electrónica MiPyMEs (FCE) B",
        [(Caea, 701, true)] = "Debe ser del tipo habilitado para CAEA - Codificación de Productos - opción Factura con Detalle y no debe estar bloqueado a la fecha en que se emitió el comprobante. Consultar método consultarPuntosVenta o consultarPuntosVentaCAEA",
        [(Caea, 702, true)] = "Debe estar comprendida dentro de la fecha desde y fecha hasta de vigencia del CAEA",
        [(Caea, 703, true)] = "El número de comprobante informado debe ser mayor en 1 al último informado para igual punto de venta y tipo de comprobante. De no existir comprobante informado para igual punto de venta y codigoTipoComprobante, el número de comprobante debe ser igual a 1 (uno)",
        [(Caea, 704, true)] = "La fecha de emisión del comprobante debe ser mayor o igual a la fecha del último comprobante informado para igual tipo de comprobante y punto de venta.",
        [(Caea, 705, true)] = "Debe informarse y corresponder a la CUIT",
        [(Caea, 706, true)] = "Debe ser mayor a la fecha de entrada en vigencia del CAEA <fechaDesde>",
        [(Caea, 707, true)] = "Si se informa uno de los campos debe informarse el otro.",
        [(Caea, 710, true)] = "Deberá ser igual a alguno de los valores permitidos. Consultar método consultarMonedas",
        [(Caea, 713, true)] = "Deberá ser igual a alguno de los siguientes valores: 1 – Productos 2 – Servicios 3 – Productos y Servicios",
        [(Caea, 715, true)] = "Opcional. Debe informarse si algún ítem tiene <codigoCondicionIVA> igual a 4, 5 ó 6.",
        [(Caea, 718, true)] = "Opcionales. Deberá informarse en los siguientes casos: - cuando <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52, 53, 201, 202, 203, 206, 207 o 208. -cuando <codigoTipoComprobante> es igual a 6, 7 u 8 y el importe total del comprobante <importeTotal> es mayor ó igual al monto en pesos resultante según RG4444.",
        [(Caea, 731, true)] = "Opcional. Si se informa debe informarse “A” (sin comillas)",
        [(Caea, 732, true)] = "Opcional. Si se informa debe coincidir con la Fecha Hasta del CAEA informado",
        [(Caea, 733, true)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52, 53, 201, 202, 203, 206, 207 o 208 <codigoTipoDocumento > deberá ser igual a 80 (CUIT)",
        [(Caea, 736, true)] = "Deberá ser igual a alguno de los valores permitidos. Consultar método consultarTiposDocumento",
        [(Caea, 739, true)] = "Los informes de comprobantes para un mismo punto de venta y tipo de comprobante deben ser enviados en forma sincrónica: si el WS recibe una nueva solicitud para un punto de venta y tipo de comprobante dado mientras la anterior está siendo procesada, la nueva solicitud será rechazada",
        [(Caea, 753, true)] = "Grupo de compradores no habilitado para el método",
        [(Caea, 754, true)] = "La fecha/hora de generación es obligatoria para comprobantes CAEA por contingencia (no se informó el campo fecha/hora generación y el punto de venta es del tipo CAEA por Contni gencia). A partir del 01/08/2026 sera obligatoria para comprobantes CAEA sin distni ción del tipo de punto de venta (por Contingencia o no)",
        [(Caea, 764, true)] = "Si <codigoTipoComprobante> es igual a 201 ó 206. La Fecha de Vencimiento de Pago es obligatorio para Facturas de Crédito MiPyME",
        [(Caea, 765, true)] = "Si <codigoTipoComprobante> es igual a 202, 203, 207 ó 208. La Fecha de Vencimiento de Pago no debe informarse para Notas de Crédito o Débito de las Facturas de Crédito MiPYME",
        [(Caea, 777, true)] = "Si <codigoTipoComprobante> es igual a 202, 203, 207 ó 208 perteneciente a Factura de Crédito Electrónica no corresponde informar un periodo de comprobantes asociados.",
        [(Caea, 778, true)] = "Si <codigoTipoComprobante> es igual a 2, 3, 7, 8, 52 ó 53. Falta informar comprobante/s asociado/s puntual del tipo factura, nota de debito o nota de crédito válido/s o informar un período de comprobantes asociados válido",
        [(Caea, 779, true)] = "Si <codigoTipoComprobante> es igual a 2, 3, 7, 8, 52 ó 53. No debe informar un período de comprobantes asociados cuando informa comprobante/s asociado/s puntual del tipo factura, nota de debito o nota de crédito",
        [(Caea, 780, true)] = "Si <codigoTipoComprobante> es igual a 1, 2, 51, 201 ó 206 correspondientes a Facturas no corresponde informar un periodo de comprobantes asociados.",
        [(Caea, 889, true)] = "Si <numeroDocumento> es la CUIT para Sujeto No Categorizado (23000000000) y el <codigoTipoDocumento> es distinto de B (6, 7 u 8) o si la <condicionIVAReceptor> no se corresponde con Sujeto No Categorizado",
        [(Caea, 803, true)] = "El comprobante asociado podrá ser: 1 – Factura A 2 – Nota de Débito A 3 – Nota de Crédito A 6 – Factura B 7 – Nota de Débito B 8 – Nota de Crédito B 51 – Factura A con leyenda OPERACIÓN SUJETA A RETENCIÓN 52 – Nota de Débito A con leyenda OPERACIÓN SUJETA A RETENCIÓN 53 – Nota de Crédito A con leyenda OPERACIÓN SUJETA A RETENCIÓN 201 - Factura de Crédito Electrónica MiPyMEs (FCE) A 202 - Nota de Débito Electrónica MiPyMEs (FCE) A 203 - Nota de Crédito Electrónica MiPyMEs (FCE) A 206- Factura de Crédito Electrónica MiPyMEs (FCE) B 207 - Nota de Débito Electrónica MiPyMEs (FCE) B 208 - Nota de Crédito Electrónica MiPyMEs (FCE) B 91 – Remito Papel 88 – Remito Electrónico de Tabaco Acondicionado 990 – Remito Electrónico de Tabaco en Hebras 993 – Remito Electrónico de Harina en Camion 994 – Remito Electrónico de Harina en Tren 995 – Remito Electrónico de Carne 997 – Remito Electrónico Azucar Mercado Interno Consultar método consultarTiposComprobante",
        [(Caea, 2800, true)] = "La fechaHasta debe ser posterior o igual fechaDesde",
        [(Caea, 2801, true)] = "La fechaHasta del periodoComprobantesAsociados debe ser anterior o igual a la fecha de emisión del comprobante por el cual se está solicitando la autorización",
        [(Caea, 900, true)] = "Valores permitidos: consultar método consultarTiposTributo",
        [(Caea, 901, true)] = "Opcional. Debe informarse si <codigo> es igual a 99.",
        [(Caea, 1000, true)] = "Valores permitidos: 4, 5, 6",
        [(Caea, 1002, true)] = "No se deberá repetir (no pueden incluírse dos subtotales IVA con el mismo código)",
        [(Caea, 1003, true)] = "Si existen uno o más ítems con una determinada alícuota IVA, deberá existir el correspondiente subtotal IVA para dicha alícuota. No se sebe incluír un subtotal IVA si dicha alícuota no está presente en al menos un ítem.",
        [(Caea, 1100, true)] = "Es opcional si <codigoUnidadMedida> es 99 ó 97, para el resto de los casos es obligatorio.",
        [(Caea, 1101, true)] = "De informarse deberá ser mayor o igual a 1 (uno)",
        [(Caea, 1102, true)] = "Longitud máxima 6 posiciones.",
        [(Caea, 1103, true)] = "Es opcional si <codigoUnidadMedida> es 99 ó 97, para el resto de los casos es obligatorio.",
        [(Caea, 1105, true)] = "Opcional. Longitud máxima 50 posiciones.",
        [(Caea, 1106, true)] = "Cantidad máxima de caracteres permitidos 4000. Importante: no es necesario (ni recomendable) completar con espacios.",
        [(Caea, 1107, true)] = "No corresponde para <codigoUnidadMedida> igual a 99 o 97. En otro caso es obligatorio.",
        [(Caea, 1108, true)] = "Debe ser alguno de los valores permitidos: consultar método consultarUnidadesMedida",
        [(Caea, 1109, true)] = "No corresponde para <codigoUnidadMedida> igual a 99 o 97. En otro caso es obligatorio.",
        [(Caea, 1110, true)] = "No corresponde para <codigoUnidadMedida> igual a 99 o 97. Es opcional para el resto de los casos.",
        [(Caea, 1111, true)] = "Deberá coincidir con alguno de los valores permitidos: consultar método consultarCondicionesIVA",
        [(Caea, 1112, true)] = "Obligatorio para <codigoTipoComprobante> igual a 1, 2, 3, 51, 52 o 53. No corresponde para <codigoTipoComprobante> igual a 6, 7 u 8.",
        [(Caea, 1121, true)] = "Si se informa el campo <unidadesMtx> entonces debe informarse el campo <codigoMtx> y viceversa.",
        [(Caea, 920, true)] = "Valores permitidos: consultar método consultarTiposDatosAdicionales",
        [(Caea, 194, true)] = "El campo es obligatorio a excepción de los casos para los cuales se envia el campo cancelaEnMismaMonedaExtranjera y se puede obtener la cotizacion asociada al codigoMoneda si esta es del grupo de monedas del Banco de la Nación Argentina (ver Anexo Monedas BNA)",
        [(Caea, 195, true)] = "No es posible indicar una cotización negativa",
        [(Caea, 708, false)] = "Si <codigoTipoDocumento> es igual a 80, 86 o 87, <numeroDocumento> debe ser válido y activo, excepto para <codigoTipoComprobante> 6, 7 u 8, <codigoTipoDocumento> 80 y <numeroDocumento> igual a 23000000000.",
        [(Caea, 717, false)] = "No debe estar informado como CAEA No utilizado",
        [(Caea, 719, false)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 o 53: - Deberá ser igual a la sumatoria de importeItem menos importeIVA para los ítems con <codigoCondicionIVA> igual a 3, 4, 5, 6. Si <codigoTipoComprobante> es igual a 6, 7 u 8: - Deberá ser igual a la sumatoria de <importeItem> menos el IVA correspondiente (calculado en base al importe y la alícuota de cada ítem), para la totalidad de los ítems con <codigoCondicionIVA> igual a 3, 4, 5 ó 6. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems gravados *",
        [(Caea, 720, false)] = "Deberá coincidir con la sumatoria de <importeItem> para los ítems con <codigoCondicionIVA> igual a 1. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems no gravados *",
        [(Caea, 721, false)] = "Deberá coincidir con la sumatoria de <importeItem> para los ítems con <codigoCondicionIVA> igual a 2. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems exentos *",
        [(Caea, 722, false)] = "Deberá coincidir con la sumatoria de los campos <importeNoGravado>, <importeGravado>, <importeExento>. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 *",
        [(Caea, 723, false)] = "Debe ser igual a la sumatoria de la totalidad de los campos <importe><otroTributo> (dentro de <arrayOtrosTributos>). Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de tributos *",
        [(Caea, 724, false)] = "Debe ser igual a <importeSubtotal>+ <importeOtrosTributos> + sumatoria de <subtotalIVA><importe> (dentro del arraySubtotalesIVA). Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 *",
        [(Caea, 725, false)] = "Debe ser igual a <importeOtrosTributos> + la sumatoria de la totalidad de los campos <importeItem>. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems *",
        [(Caea, 122, false)] = "En caso de enviar la marca de que el pago del comprobante se realiza en la misma moneda extranjera para comprobantes que no sean facturas. Unicamente se puede utilizar con los códigos habilitados (1,6,51,201,206)",
        [(Caea, 182, false)] = "No podrá ser inferior al 2% ni superior en un 400% del que suministra ARCA como orientativo de acuerdo a la cotización oficial",
        [(Caea, 726, false)] = "Debe ser igual a 1 (uno) si <codigoMoneda> es igual a PES",
        [(Caea, 174, false)] = "En caso de enviar un valor inválido para la marca de que el pago de la factura se realiza en la misma moneda extranjera. Los valores válidos son S, N o vacío",
        [(Caea, 175, false)] = "En caso de enviar la marca de que el pago de la factura se realiza en la misma moneda extranjera y enviar como código de moneda el Peso Argentino",
        [(Caea, 727, false)] = "Debe informarse solo si <codigoConcepto> es igual a 2 ó 3. En otro caso no corresponde.",
        [(Caea, 728, false)] = "Debe informarse solo si <codigoConcepto> es igual a 2 ó 3. En otro caso no corresponde.",
        [(Caea, 729, false)] = "Debe informarse solo si <codigoConcepto> es igual a 2 ó 3. En otro caso no corresponde.",
        [(Caea, 730, false)] = "La fecha de vencimiento de pago debe ser mayor o igual a la fecha de emisión.",
        [(Caea, 734, false)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 o 53 la CUIT del receptor debe encontrarse activa en IVA o en monotributo.",
        [(Caea, 735, false)] = "El Receptor no puede ser igual al Emisor",
        [(Caea, 737, false)] = "La Fecha de Servicio desde debe ser menor o igual a la Fecha de Servicio Hasta",
        [(Caea, 749, false)] = "Falta incluir en la sección OtrosTributos la Percepción de IVA No Categorizado (ID 13), según lo dispuesto por la RG 2126/2006. Se debe informar el tributo <codigo> 13 (Percepción de IVA No Categorizado) con un <importe> mayor a 0 (cero) dentro del nodo <arrayOtrosTributos> cuando se cumplan simultáneamente las siguientes condiciones: - <codigoTipoComprobante> corresponda a un comprobante clase B (6, 7 u 8). - <codigoTipoDocumento> sea igual a 80 (CUIT). - <numeroDocumento> corresponda a 23000000000 (No Categorizado). - La suma de <importeGravado> más la sumatoria de los campos <importe> dentro de <arraySubtotalesIVA> sea mayor a 0 (cero).",
        [(Caea, 750, false)] = "Debe estar dado de alta en el Impuesto al Valor Agregado al momento de la fecha de emisión del comprobante",
        [(Caea, 782, false)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 ó 53 la CUIT del receptor es activa en monotributo",
        [(Caea, 366, false)] = "Si <codigo> se encuentra mas de una vez en el array de actividades (no admite repetidos). Ver el Anexo de Rubros de Actividades y Remitos",
        [(Caea, 367, false)] = "Si <codigo> no se encuentra entre las actividades vigentes para la cuit representada. Ver el Anexo de Rubros de Actividades y Remitos",
        [(Caea, 390, false)] = "Si no se informa la condición de IVA del Receptor (obligatoria) o bien se informa un valor no contemplado por el servicio. Ver método consultarCondicionesIVARecep tor",
        [(Caea, 391, false)] = "A partir del 5 de abril de 2025 podrá enviarse de forma opcional el campo Condición Frente al IVA del receptor, hasta tanto entre en vigencia su obligatoriedad reglamentada por la Resolución General N° 5616, en cuyo momento pasará a rechazar la emisión de comprobantes sin este dato. Si se informa una combinación invalida de Condición de IVA del Receptor y Tipo de Comprobante. Ver método consultarCondicionesIVARecep tor",
        [(Caea, 1001, false)] = "Para comprobantes clase “A”: Deberá coincidir con la sumatoria de todos los <importeIVA> de <item> donde la alícuota de IVA coincida con la indicada, es decir, donde <codigoCondicionIVA> de <item> = <codigo> de <subtotalIVA>. Para comprobantes clase “B”: Deberá coincidir con la sumatoria de todos los importes IVA calculados en base al importe y alícuota IVA de <item> donde la alícuota de IVA coincida con la indicada, es decir, donde <codigoCondicionIVA> de <item> = <codigo> de <subtotalIVA>. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems con igual código de alícuota de IVA *",
        [(Caea, 1005, false)] = "La suma de los subtotales de IVA no puede ser negativa.",
        [(Caea, 1114, false)] = "De informarse deberá ser menor o igual a <precioUnitario>*<cantidad>",
        [(Caea, 1115, false)] = "Si <codigoUnidadMedida> es 99 deberá existir por lo menos otro item con igual <codigoCondicionIVA> y <codigoUnidadMedida> distinta a la informada para este item.",
        [(Caea, 1116, false)] = "Para <codigoTipoComprobante> igual a 1, 2, 3, 51, 52 o 53 y unidad de medida es distinto a 95, 97 o 99 deberá ser igual (<precioUnitario> * <cantidad> -<importeBonificación>) * alícuota de IVA correspondiente. Para <codigoTipoComprobante> igual a 1, 2, 3, 51, 52 o 53 y unidad de medida igual a 95 deberá ser igual a (-1) * (<precioUnitario> * <cantidad> - <importeBonificacion>) * alícuota de IVA correspondiente. Para <codigoTipoComprobante> igual a 1, 2, 3, 51, 52 o 53 y unidad de medida igual a 97 o 99, deberá ser igual a <importeItem> - <importeItem> / (1 + alícuota de IVA correspondiente).",
        [(Caea, 1117, false)] = "Si <codigoTipoComprobante> es igual a 1, 2 ó 3 y <codigoUnidadMedida> es 99, el valor absoluto de la sumatoria de los importes ingresados para este campo no puede superar a la sumatoria de los importes <importeIVA> informado con la misma alícuota.",
        [(Caea, 1118, false)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 o 53 y <codigoUnidadMedida> es: - 99 deberá ser menor o igual a 0 (cero), - 97 podrá ser menor, mayor o igual a 0 (cero). - 95 deberá ser menor o igual a 0 (cero), - Cualquier otro caso deberá ser mayor o igual a 0 (cero)",
        [(Caea, 1119, false)] = "Si <codigoUnidadMedida> es: - 99 deberá ser menor a 0 (cero), - 97 podrá ser menor, mayor o igual a 0 (cero) - 95 deberá ser menor a 0 (cero), - Cualquier otro caso deberá ser mayor o igual a 0 (cero).",
        [(Caea, 1120, false)] = "Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 o 53 y <codigoUnidadMedida> es distinto a 95, 97 ó 99 deberá ser igual a (<precioUnitario> sin IVA *<cantidad> -<importeBonificacion>)*(1+alícuota). Si <codigoTipoComprobante> es igual a 1, 2, 3, 51, 52 o 53 y <codigoUnidadMedida> es igual a 95 deberá ser igual a (-1) * (<precioUnitario> sin IVA * <cantidad> -<importeBonificacion>)*(1+alícuota). Si <codigoTipoComprobante> es igual a 6, 7 u 8 y <codigoUnidadMedida> es distinto a 95, 97 ó 99 deberá ser igual a (<precioUnitario> con IVA * <cantidad> - <importeBonificacion>). Si <codigoTipoComprobante> es igual a 6, 7 u 8 y <codigoUnidadMedida> es igual a 95 ser igual a (-1) * (<precioUnitario> con IVA * <cantidad> - <importeBonificacion>). En ambos casos el error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 *",
        [(Caea, 1122, false)] = "Si <codigoCondicionIVA> es igual a 1, 2, 3, 51, 52 o 53 entonces <importeIVA> deberá ser igual a 0 (cero).",
        [(Request, 600, true)] = "Debe tener el formato AAAAMM, donde AAAA indica el año y MM el mes en números.",
        [(Request, 601, true)] = "Debe ser igual a 1 ó 2.",
        [(Request, 602, true)] = "Fecha de envío podrá ser hasta 5 (cinco) días corridos anteriores del inicio cada quincena y hasta el final de la misma.",
        [(Request, 604, true)] = "No debe existir un CAEA otorgado para la CUIT solicitante con igual periodo y orden.",
        [(Request, 10024, true)] = "Deberá poseer al menos un punto de venta activo correspondiente al régimen CAEA - Codificación de Productos - opción Facturas con Detalle",
        [(Request, 10027, true)] = "Se recuerda que según la RG 5782/2025 el régimen de CAEA se aplica exclusivamente a situaciones de contingencia, motivo por el cual solo se permitirá su uso en domicilios que cuenten con al menos un punto de venta activo bajo la modalidad CAE o Controlador Fiscal como modalidad principal",
        [(Request, 10000, true)] = "Debe encontrarse activa en el Sistema Registral",
        [(Request, 10003, true)] = "Debe estar dado de alta en el Impuesto al Valor Agregado al momento del envío de la solicitud.",
        [(Unused, 1200, true)] = "Debe ser del tipo de código de autorización CAEA",
        [(Unused, 1201, true)] = "Corresponda a la CUIT indicada en <cuitRepresentada>",
        [(Unused, 1203, true)] = "La fecha de envío de la solicitud debe ser mayor a la fecha de inicio de vigencia del CAEA que se está informando.",
        [(Unused, 1204, true)] = "Debe corresponder a un punto de venta CAEA",
        [(Unused, 1206, true)] = "No debe estar informado como utilizado en algún comprobante para el punto de venta indicado",
        [(Unused, 1207, true)] = "No debe estar informado como no utilizado para el punto de venta indicado",
        [(Unused, 1202, true)] = "No debe estar informado como utilizado en algún comprobante",
        [(Unused, 1208, true)] = "No debe estar informado como no utilizado",
        [(Query, 1300, true)] = "Debe ser un CAEA previamente otorgado",
        [(Query, 1301, true)] = "Debe corresponder a la CUIT indicada en <cuitRepresentada>",
        [(Query, 1400, true)] = "fechaDesde debe ser menor o igual a fechaHasta",
        [(Query, 1500, true)] = "Podrá ser: 1 – Factura A 2 – Nota de Débito A 3 – Nota de Crédito A 6 – Factura B 7 – Nota de Débito B 8 – Nota de Crédito B 51 – Factura A con leyenda OPERACIÓN SUJETA A RETENCIÓN 52 – Nota de Débito A con leyenda OPERACIÓN SUJETA A RETENCIÓN 53 – Nota de Crédito A con leyenda OPERACIÓN SUJETA A RETENCIÓN Consultar método consultarTiposComprobante",
        [(Query, 1501, true)] = "Debe ser del tipo habilitado para el régimen CAE Codificación de Productos – Web Services ó del régimen CAEA. Consultar método consultarPuntosVenta, consultarPuntosVentaCAE o consultarPuntosVentaCAEA.",
        [(Query, 1502, true)] = "Debe obrar en las bases del organismo al menos un comprobante emitido con el tipo de comprobante y punto de ventas indicados.",
        [(Query, 1503, true)] = "Deberá obrar en las bases del organismo un comprobante con el tipo, punto de venta y número de comprobante indicados.",
        [(Query, 196, true)] = "En caso de no estar contemplado dentro de los tipos de comprobantes validos para el servicio",
        [(Query, 1600, true)] = "Deberá coincidir con alguno de los códigos de moneda disponibles. Consultar método consultarMonedas",
    };
}
