namespace ArcaSim.Application.Services.TurismoBonos;

/// <summary>
/// The business codes of the wsct manual (v1.6.4) with their texts, as
/// docs/arca/servicios/wsct-codigos.json has them. The manual gives the
/// condition each code checks, not the descripcion the service sends, so the
/// condition is what ArcaSim answers.
/// </summary>
internal static class WsctCodes
{
    private static readonly Dictionary<int, string> Texts = new()
    {
        [100] = "El emisor del comprobante debe encontrarse activo en el sistema registral.",
        [101] = "El emisor del comprobante debe estar empadronado en alguna actividad de hospedaje/turismo.",
        [102] = "El emisor del comprobante no debe tener domicilios con inconsistencias.",
        [103] = "El emisor del comprobante debe estar registrado en el impuesto al Valor Agregado al momento de autorizar el comprobante.",
        [104] = "El emisor del comprobante debe tener un punto de venta habilitado a “RECE para aplicativo y web services” o “Codificación de producto - Web services”, vigente, no bloqueado y no dado de baja.",
        [200] = "Informar el campo codigoTipoAutorizacion según el tipo de autorización a efectuar. Siempre debe informarse.",
        [201] = "Solo se encuentra disponible la modalidad de autorización E = CAE",
        [202] = "Si informa <codigoTipoAutorizacion> = “E”, no informar el código de autorización.",
        [203] = "Si informa <codigoTipoAutorizacion> = “E”, no informar la fecha de vencimiento del código de autorización.",
        [300] = "El tipo de comprobante debe corresponder a alguno de los comprobantes habilitados. Ver el método consultarTiposComprobantes().",
        [301] = "El punto de venta debe ser un punto de venta habilitado. Consultar el método consultarPuntosVenta().",
        [302] = "La numeración no corresponde con el próximo a autorizar. Consultar método consultarUltimoComprobanteAutorizado().",
        [303] = "Si se envía puede ser hasta 10 días anteriores o posteriores a la fecha de generación. Si no se envía se le asignará la fecha de proceso",
        [304] = "El tipo de moneda debe ser alguno de los tipos de moneda habilitados. Consultar el método consultarMonedas().",
        [305] = "Si el código de moneda es PES, la cotización debe ser 1.",
        [306] = "El tipo de cambio no podrá ser inferior al 2% ni superior en un 400% del que suministra ARCA como orientativo de acuerdo a la cotización oficial. Consultar método consultarCotizacion().",
        [307] = "El código de país debe ser uno de los habilitados. Consultar el método consultarPaises().",
        [308] = "El identificador impositivo o condición de IVA del receptor debe ser uno de los habilitados. Consultar el método consultarCondicionesIVA().",
        [309] = "Cuando informa identificador impositivo “IVA Responsable Inscripto” el tipo de documento debe ser CUIT.",
        [310] = "Cuando informa identificador impositivo “IVA Responsable Inscripto”, con tipo de documento CUIT, el número de documento debe encontrarse registrado en las bases de esta administración de forma activa.",
        [311] = "Cuando informa identificador impositivo “Consumidor Final”, los tipos de documentos habilitados para informar sobre el receptor son CUIT país / CI Extranjera / Pasaporte / DNI.",
        [312] = "Cuando informa identificador impositivo “Consumidor Final”, el número de documento debe ser un valor alfanumérico.",
        [313] = "Cuando informa identificador impositivo “Cliente del Exterior”, los tipos de documentos habilitados para informar sobre el receptor son CUIT país, CI Extranjera / Pasaporte / DNI.",
        [314] = "Cuando informa identificador impositivo “Cliente del Exterior”, con tipo de documento CUIT, es obligatorio informar un CUIT País habilitado. Consultar método consultarCUITsPaises()",
        [315] = "Cuando informa identificador impositivo “Cliente del Exterior”, el número de documento debe ser un valor alfanumérico.",
        [316] = "Cuando informa identificador impositivo “IVA Responsable Inscripto”, con tipo de documento CUIT, el número de documento debe encontrarse registrado en las bases de esta en el Impuesto al Valor Agregado.",
        [317] = "Deberá debe ser mayor a cero",
        [318] = "En caso de enviar la marca de que el pago del comprobante se realiza en la misma moneda extranjera para comprobantes que no sean facturas. Unicamente se puede utilizar con los códigos habilitados (195)",
        [319] = "En caso de enviar la marca de que el pago de la factura se realiza en la misma moneda extranjera y enviar como código de moneda el Peso Argentino",
        [320] = "En caso de enviar la marca de que el pago de la factura se realiza en la misma moneda extranjera, que codigoMoneda es del grupo de monedas con cotización del Banco de la Nación Argentina (ver Anexo Monedas BNA), que haya cotización y que la misma no coincida exactamente con el valor enviado en el campo cotizacionMoneda. En cuyo caso se podrá omitir el mismo para que la cotización de la factura sea la obtenida de los registros de ARCA",
        [322] = "El campo es obligatorio a excepción de los casos para los cuales se envia el campo cancelaEnMismaMonedaExtranjera y se puede obtener la cotizacion asociada al codigoMoneda si esta es del grupo de monedas del Banco de la Nación Argentina (ver Anexo Monedas BNA)",
        [350] = "El domicilio del receptor es obligatorio informarlo. Su dimensión máxima son 300 caracteres alfanuméricos.",
        [351] = "La relación entre el emisor y el receptor debe ser alguna de las habilitadas. Consultar el método consultarRelacionEmisorReceptor()",
        [352] = "Si el tipo de relación Emisor Receptor seleccionada corresponde a: 1 - Alojamiento Directo a Turista No Residente 2 - Alojamiento a Agencia de Viaje Residente 3 - Alojamiento a Agencia de Viaje No Residente el emisor debe tener al menos una actividad de hospedaje vigente. Si el tipo de relación es: 4 - Agencia de Viaje Residente a Agencia de Viaje No Residente 5 - Agencia de Viaje Residente a Turista No Residente 6 - Agencia de Viaje Residente a Agencia de Viaje Residente el emisor debe estar registrado en el padrón de agencias de la secretaría de turismo.",
        [353] = "Cuando la relación Emisor Receptor es: 1 - Alojamiento Directo a Turista No Residente / 5 - Agencia de Viaje Residente a Turista No Residente, los tipos de documentos de receptor habilitados son 80 - Cuit / 91 - CI Extranjera / 94 - Pasaporte / 96 – DNI Cuando es: 2 - Alojamiento a Agencia de Viaje Residente / 3 - Alojamiento a Agencia de Viaje No Residente / 4 - Agencia de Viaje Residente a Agencia de Viaje No Residente / 6 - Agencia de Viaje Residente a Agencia de Viaje Residente El tipo de documento habilitado es 80 – CUIT",
        [354] = "Al momento de informar emisor y receptor, los mismos deben ser distintos.",
        [355] = "Si el tipo de relación Emisor Receptor seleccionada corresponde a 1,3,4 o 5, el código de país informado no podrá ser 200 – Argentina ni los sig. valores sig. valores 295, 296 y rango 250 al 265. Si el tipo de relación es 2 o 6, el código de país informado deberá ser 200 – Argentina.",
        [356] = "Si el identificador impositivo es IVA Responsable Inscripto, la relación emisor receptor debe ser 2 o 6. Si el identificador impositivo es Consumidor final o Cliente del Exterior y el tipo de documento es 80 - CUIT, la relación debe ser 3 o 4. Si el identificador impositivo es Consumidor final o Cliente del Exterior y el tipo de documento es 91 - CI Extranjera / 94 - Pasaporte / 96 – DNI, la relación debe ser 1 o 5.",
        [360] = "Es obligatorio informarlo y debe ser mayor o igual a cero.",
        [361] = "Deberá coincidir con la sumatoria de <importeItem> menos el IVA correspondiente <importeIVA>(calculado en base al importe y la alícuota de cada ítem), para la totalidad de los ítems. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems gravados *",
        [362] = "No informar el campo. Previsto para alícuotas de IVA futuras. Si informa el campo, el mismo debe venir en cero.",
        [363] = "No informar el campo. Previsto para alícuotas de IVA futuras. Si informa el campo, el mismo debe venir en cero.",
        [364] = "El campo <importeReintegro> debe ser informado, menor o igual a cero si dentro del array de item existe al menos un item con <codigoTurismo> igual a 1 - Servicio de hotelería - alojamiento sin desayuno / 2 - Servicio de hotelería - alojamiento con desayuno.",
        [365] = "El campo <importeReintegro> no debe ser informado o ser igual a 0 por tener todos sus items con <codigoTurismo> igual a 5 - Excedente cuando el tipo de comprobante es 196 - Nota de Débito T / 197 - Nota de Crédito T",
        [366] = "El campo <importeReintegro> debe ser igual a la sumatoria de los importes de iva de todos los ítems que tengan <codigoTurismo> igual a 1 - Servicio de hotelería - alojamiento sin desayuno / 2 - Servicio de hotelería - alojamiento con desayuno Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de ítems gravados con código de turismo igual a 1 - Servicio de hotelería - alojamiento sin desayuno / 2 - Servicio de hotelería - alojamiento con desayuno *",
        [367] = "Si informa el campo, el mismo debe ser mayor o igual a cero.",
        [368] = "La sumatoria de campos importe de otros tributos debe ser igual al campo <importeOtrosTributos>. Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 * cantidad de tributos *",
        [369] = "El importe total debe ser igual a la sumatoria de los campos: <importeGravado>, <importeNoGravado>, <importeExento>, <importeReintegro>, <importeOtrosTributos>, sumatoria de <subtotalIVA><importe> (dentro del arraySubtotalesIVA). Margen de error: Error relativo porcentual deberá ser <= 0.01% o el error absoluto <=0.01 *",
        [400] = "Al momento de informar los ítems, el tipo de ítem debe ser alguno de los habilitados. Consultar el método consultarTiposItem()",
        [401] = "Al momento de informar los códigos de turismo, informar alguno de los habilitados. Consultar el método consultarCodigosItemTurismo()",
        [403] = "Al momento de identificar la alícuota de IVA aplicada al ítem verificar que solo se corresponda con el código 5 - 21%",
        [404] = "Es obligatorio identificar la descripción del ítem. Su dimensión no puede superar los 4000 caracteres alfanuméricos y no puede venir vacío.",
        [406] = "Si el tipo de ítem es 0 - Item general el importe del item debe ser mayor o igual a 0 (cero).",
        [407] = "Si el tipo de ítem es 97 - Anticipo se aceptan importes positivos o negativos.",
        [408] = "Si el tipo de ítem es 99 - Descuento General, el importe deberá ser negativo.",
        [409] = "Si el tipo de ítem es 0 - Item general el importe IVA del ítem debe ser mayor o igual a 0 (cero).",
        [410] = "Si el tipo de ítem es 97 - Anticipo se aceptan importes de importe IVA positivos o negativos.",
        [411] = "Si el tipo de ítem es 99 - Descuento General, el importe de IVA deberá ser negativo.",
        [412] = "La alícuota de IVA debe ser del tipo (5 - 21%).",
        [413] = "Aplicando el porcentaje de IVA al importe del ítem <importeItem>, el valor resultante debe ser igual al importe de IVA <importeIVA> informado.",
        [414] = "El signo del campo <importeIVA> debe corresponder con el signo <importeItem>",
        [415] = "Para comprobantes 195 - Factura T, no se permite facturar solo (codigoTurismo) 5 – Excedente.",
        [500] = "El array de subtotales de IVA es obligatorio informarlo",
        [501] = "Al momento de informar los subtotales de IVA, informar códigos habilitados. Consultar método consultarTiposIVA().",
        [502] = "No se permite repetir los códigos de los subtotales de IVA.",
        [503] = "El campo importe de subtotales de IVA es obligatorio informarlo y mayor o igual a cero.",
        [504] = "La suma de todos importes de IVA del array de IVA para la misma alícuota debe ser igual al valor identificado en el campo importe de subtotales de IVA para la alícuota en cuestión.",
        [600] = "El código de tributo debe corresponder con alguno de los habilitados. Consultar el método consultarTiposTributo()",
        [602] = "La descripción de otros tributos puede no informarse. Si se informa, su dimensión no puede superar los 50 caracteres alfanuméricos. Es obligatoria para <codigo> 99 – Otro.",
        [603] = "El campo base imponible puede no informarse. Si se informa, debe contener un valor mayor o igual a cero.",
        [604] = "El campo importe debe informarse con un valor mayor o igual a cero.",
        [700] = "Verificar que el código sea uno de los habilitados. Consultar el método consultarFormasPago()",
        [701] = "Si el código de forma de pago hace referencia a Tarjeta de Débito o Crédito, no informar código SWIFT.",
        [702] = "Si el código de forma de pago hace referencia a Tarjeta de Débito o Crédito, no informar tipo de cuenta.",
        [703] = "Si el código de forma de pago hace referencia a Tarjeta de Débito o Crédito, no informar número de cuenta.",
        [704] = "Si el código de forma de pago hace referencia a Tarjeta de Débito o Crédito, el tipo de tarjeta es obligatorio informarlo y debe ser un tipo habilitado. Consultar el método consultarTiposTarjeta().",
        [705] = "Si el código de forma de pago hace referencia a Tarjeta de Débito o Crédito, el número de tarjeta es obligatorio informarlo y solo los primeros 6 caracteres.",
        [720] = "Si el código de forma de pago hace referencia a Transferencia Bancaria, no informar tipo de tarjeta.",
        [721] = "Si el código de forma de pago hace referencia a Transferencia Bancaria, no informar número de tarjeta",
        [722] = "Si el código de forma de pago hace referencia a Transferencia Bancaria, es obligatorio informar el tipo de cuenta y debe estar habilitado. Consultar el método consultarTiposCuenta().",
        [723] = "Si el código de forma de pago hace referencia a Transferencia Bancaria, informar un n° de cuenta válido.",
        [724] = "Si el código de forma de pago hace referencia a Transferencia Bancaria e informa un código Swift, el mismo debe corresponder a un código Swift de Argentina cuando <codigoRelacionEmisorReceptor> es 2 o 6. Y del exterior cuando <codigoRelacionEmisorReceptor> es 1,3,4 o 5.",
        [730] = "Si el código de forma de pago hace referencia a Cuenta Corriente no informar los tags <tipoTarjeta> <numeroTarjeta> <swiftCode> <tipoCuenta> <numeroCuenta>",
        [731] = "Si el código de forma de pago hace referencia a Cuenta Corriente, solo puede informarse una sola vez en el array.",
        [732] = "Si el código de forma de pago hace referencia a Cuenta Corriente, <codigoRelacionEmisorReceptor> debe ser 2 o 6",
        [800] = "Si el tipo de comprobante es 195 – Factura T, no asociar comprobantes. Si el tipo de comprobante a autorizar es 196 - Nota de Débito T o 197 - Nota de Crédito T es obligatorio informar comprobantes asociados.",
        [801] = "Al momento de asociar un comprobante, el tipo de comprobante asociado debe ser alguno de los habilitados. Consultar método consultarTiposComprobantes().",
        [803] = "El comprobante asociado debe pertenecer a un comprobante registrado y autorizado en las bases de esta administración donde los emisores de ambos sean iguales. De ser electrónicos deberían ser iguales los receptores.",
        [804] = "No se permite informar comprobantes asociados repetidos.",
        [805] = "La fecha de emisión del comprobante a autorizar debe ser mayor o igual a la fecha del comprobante asociado",
        [806] = "El receptor del comprobante a autorizar debe coincidir con el receptor del comprobante asociado",
        [807] = "Cuando se requiere autorizar un comprobante de Tipo Nota de Crédito, y el importe de la misma, supera el monto del o los comprobante/s asociado/s que esta ajustando.",
        [900] = "Si informa datos adicionales, verificar que sea uno de los datos habilitados. Consultar método consultarTiposDatosAdicionales()",
        [2000] = "Evaluar que el tipo de comprobante que se está consultando sea uno habilitado a usar en el ws actual. Consultar el método consultarTiposComprobantes().",
        [2001] = "Evaluar si el punto de venta se encuentra habilitado a utilizar en el servicio en cuestión.",
        [2002] = "Debe tener al menos un comprobante emitido para la combinación CUIT, punto de venta y tipo de comprobante",
        [1000] = "Evaluar que el tipo de comprobante que se está consultando sea uno habilitado a usar en el ws actual. Consultar el método consultarTiposComprobantes().",
        [1001] = "Evaluar si el punto de venta se encuentra habilitado a utilizar en el servicio en cuestión.",
        [1002] = "Debe tener al menos un comprobante emitido para la combinación CUIT, punto de venta y tipo de comprobante",
        [1106] = "Deberá contener al menos un punto de venta habilitado a utilizar con el presente ws",
        [210] = "Deberá coincidir con alguno de los códigos de moneda disponibles. Consultar método consultarMonedas",
        [1200] = "Deberá coincidir con las formas de pago posibles 1 - debito, 2 - crédito. Consultar método consultarFormasPago",
    };

    public static BookNote Note(int code) => new(code, Texts[code]);
}
