<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ArcaSim.Infrastructure\ArcaSim.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\docs\arca\wsdl\wsaa-*.wsdl;..\..\docs\arca\wsdl\wsfev1-*.wsdl" LogicalName="ArcaSim.Wsdl.%(Filename)%(Extension)" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
