namespace ArcaSim.Application.Wsfe;

/// <summary>
/// A detail validation, independent of the code it carries. FECAESolicitar and
/// FECAEARegInformativo check much the same things under different numbers
/// (and often with a different effect: CAEA observes where CAE rejects).
/// </summary>
public enum Rule
{
    FromRange,
    ToRange,
    BatchOrder,
    SingleNumber,
    SingleNumberClassC,
    ClassADocumentType,
    BatchOverThreshold,
    BatchToConsumer,
    IdentifyOverThreshold,
    ConsumerNumberZero,
    DocumentNumberRequired,
    UnknownDocumentType,
    ReceiverNotRegistered,
    UsedGoodsReceiver,
    FceDocumentType,
    ReceiverInactiveClassA,
    ReceiverNotInVatClassA,
    MonotributoReceiver,
    NotCategorizedPerceptionMissing,
    NotCategorizedPerceptionObserved,
    SameAsIssuer,
    FutureMonth,
    ServiceDatesRequired,
    ServiceFromMissing,
    ServiceToMissing,
    PaymentDueMissing,
    DateFormat,
    ServiceOrder,
    PaymentDueBeforeDate,
    NotTaxedNegative,
    NotTaxedClassC,
    ExemptNegative,
    ExemptClassC,
    NetNegative,
    OtherTaxesNegative,
    VatNegative,
    VatClassC,
    TotalNegative,
    TotalMismatch,
    TotalMismatchClassC,
    Precision,
    VatOnClassC,
    VatMissing,
    NetWithoutVat,
    VatId,
    VatBase,
    VatAmount,
    VatDuplicate,
    VatSum,
    VatRateAmount,
    NetSum,
    OtherTaxesPresence,
    OtherTaxId,
    OtherTaxBase,
    OtherTaxRate,
    OtherTaxAmount,
    OtherTaxesSum,
    OtherTaxDescription,
    Concept,
    UsedGoodsConcept,
    Currency,
    SameCurrencyFlag,
    PesosSameCurrency,
    PesosRate,
    Rate,
    RateRange,
    ReceiverConditionMissingObserved,
    ReceiverConditionMissingRequired,
    ReceiverConditionUnknown,
    ReceiverConditionClass,
    NoteWithoutAssociated,
    InvoiceWithPeriod,
    AssociatedType,
    AssociatedPointOfSale,
    AssociatedNumber,
}

/// <summary>
/// The code each rule carries in each method, from the manual's tables
/// (docs/arca/wsfev1-codigos.md §4.1 and §4.2). Null where the method has no
/// such check.
/// </summary>
public static class RuleCodes
{
    public const string Cae = "FECAESolicitar";
    public const string Caea = "FECAEARegInformativo";

    private static readonly Dictionary<Rule, (int? Cae, int? Caea)> Codes = new()
    {
        [Rule.FromRange] = (10008, 784),
        [Rule.ToRange] = (10010, 784),
        [Rule.BatchOrder] = (10011, 1416),
        [Rule.SingleNumber] = (10012, 711),
        [Rule.SingleNumberClassC] = (10012, 1433),
        [Rule.ClassADocumentType] = (10013, 1403),
        [Rule.BatchOverThreshold] = (10014, 1422),
        [Rule.BatchToConsumer] = (10015, 1415),
        [Rule.IdentifyOverThreshold] = (10015, 1417),
        [Rule.ConsumerNumberZero] = (10015, 1418),
        [Rule.DocumentNumberRequired] = (10015, 1419),
        [Rule.UnknownDocumentType] = (10015, 1404),
        [Rule.ReceiverNotRegistered] = (10015, 1420),
        [Rule.UsedGoodsReceiver] = (10015, null),
        [Rule.FceDocumentType] = (10015, 1487),
        [Rule.ReceiverInactiveClassA] = (10017, 708),
        [Rule.ReceiverNotInVatClassA] = (10063, 1402),
        [Rule.MonotributoReceiver] = (10217, 1516),
        [Rule.NotCategorizedPerceptionMissing] = (10067, 1425),
        [Rule.NotCategorizedPerceptionObserved] = (10283, 1425),
        [Rule.SameAsIssuer] = (10069, 788),
        [Rule.FutureMonth] = (10152, null),
        [Rule.ServiceDatesRequired] = (10049, null),
        [Rule.ServiceFromMissing] = (10031, null),
        [Rule.ServiceToMissing] = (10033, null),
        [Rule.PaymentDueMissing] = (10035, null),
        [Rule.DateFormat] = (10049, 1413),
        [Rule.ServiceOrder] = (10032, 1412),
        [Rule.PaymentDueBeforeDate] = (10036, 1411),
        [Rule.NotTaxedNegative] = (10043, 717),
        [Rule.NotTaxedClassC] = (10043, 1434),
        [Rule.ExemptNegative] = (10044, 718),
        [Rule.ExemptClassC] = (10044, 1435),
        [Rule.NetNegative] = (10045, 719),
        [Rule.OtherTaxesNegative] = (10046, 723),
        [Rule.VatNegative] = (10047, 1407),
        [Rule.VatClassC] = (10047, 1438),
        [Rule.TotalNegative] = (10065, 1409),
        [Rule.TotalMismatch] = (10048, 724),
        [Rule.TotalMismatchClassC] = (10048, 1439),
        [Rule.Precision] = (10056, null),
        [Rule.VatOnClassC] = (10071, 1443),
        [Rule.VatMissing] = (10018, 715),
        [Rule.NetWithoutVat] = (10070, 1427),
        [Rule.VatId] = (10019, 1000),
        [Rule.VatBase] = (10020, 1009),
        [Rule.VatAmount] = (10021, 1008),
        [Rule.VatDuplicate] = (10022, 1003),
        [Rule.VatSum] = (10023, 725),
        [Rule.VatRateAmount] = (10051, 1006),
        [Rule.NetSum] = (10061, 1408),
        [Rule.OtherTaxesPresence] = (10024, 1423),
        [Rule.OtherTaxId] = (10025, 900),
        [Rule.OtherTaxBase] = (10026, 905),
        [Rule.OtherTaxRate] = (10027, 906),
        [Rule.OtherTaxAmount] = (10028, 907),
        [Rule.OtherTaxesSum] = (10029, 1406),
        [Rule.OtherTaxDescription] = (10042, 908),
        [Rule.Concept] = (10030, 713),
        [Rule.UsedGoodsConcept] = (10085, null),
        [Rule.Currency] = (10037, 1401),
        [Rule.SameCurrencyFlag] = (10239, 820),
        [Rule.PesosSameCurrency] = (10241, 822),
        [Rule.PesosRate] = (10039, 726),
        [Rule.Rate] = (10038, 726),
        [Rule.RateRange] = (10119, null),
        [Rule.ReceiverConditionMissingObserved] = (10245, 825),
        [Rule.ReceiverConditionMissingRequired] = (10246, 826),
        [Rule.ReceiverConditionUnknown] = (10242, 823),
        [Rule.ReceiverConditionClass] = (10243, 824),
        [Rule.NoteWithoutAssociated] = (10197, 1491),
        [Rule.InvoiceWithPeriod] = (10198, 1492),
        [Rule.AssociatedType] = (10040, 807),
        [Rule.AssociatedPointOfSale] = (10058, 802),
        [Rule.AssociatedNumber] = (10059, 803),
    };

    public static int? CodeOf(Rule rule, string method) =>
        method == Caea ? Codes[rule].Caea : Codes[rule].Cae;

    public static IEnumerable<(Rule Rule, int? Cae, int? Caea)> All =>
        Codes.Select(pair => (pair.Key, pair.Value.Cae, pair.Value.Caea));
}
